server:
  servlet:
    context-path: /api/evaluation

# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teaching_evaluation_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#上传文件配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印日志
    #log-impl:org.apache.ibatis.logging.slf4j.Slf4jImpl  #文件打印日志
    map-underscore-to-camel-case: true  #开启驼峰命名法
  mapper-locations:
    - classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  global-config:
    db-config:
      id-type: auto #全局自增
